{
  "comments": [
    {
      "key": {
        "uuid": "ae0e4726_da2561be",
        "filename": "docs/conf.py",
        "patchSetId": 3
      },
      "lineNbr": 8,
      "author": {
        "id": 1001
      },
      "writtenOn": "2014-03-26T15:30:57Z",
      "side": 1,
      "message": "I have no idea why tox decided to start complaining about this suddenly.",
      "revId": "a57b7748b72b3cf1af87e6a9b8791f61b2d24b10",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951",
      "unresolved": false
    }
  ]
}